### ISSUE TITLE
Vim: Caught deadly signal SEGV Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by duyhtq** [klen/python-mode#445]
i just added python-mode to vim

whenever i save and quit (:wq), i also got this error

Vim: Caught deadly signal SEGV
Segmentation fault (core dumped)

anh suggestion on how to fix this is much appreciated

**Comment by smyrman** [comment]
Hi guys. I am not sure if this is related, but I got a similar error

Vim: Caught deadly signal SEGV
Segmentation fault (core dumped)

For me, the error was caused by outdated Intel processor microcode actually, and updating my microcode as described here, solved the problem.

- Microcode update instructions: https://wiki.archlinux.org/index.php/Microcode (can also be done from BIOS/UEFI)
- Forum post: https://bbs.archlinux.org/viewtopic.php?id=196667

**Comment by krader1961** [comment]
On Fri, May 22, 2015 at 11:45 PM, Sindre Røkenes Myren <
notifications@github.com> wrote:

> Hi guys. I am not sure if this is related, but I got a similar error
>
> Vim: Caught deadly signal SEGV
> Segmentation fault (core dumped)
>
> For me, the error was caused by outdated Intel processor microcode
> actually, and updating my microcode as described here, solved the problem.
>
>    - Microcode update instructions:
>    https://wiki.archlinux.org/index.php/Microcode (can also be done from
>    BIOS/UEFI)
>    - Forum post: https://bbs.archlinux.org/viewtopic.php?id=196667
>
>
That is an excellent observation. In my previous job I specialized in
debugging such problems. Had you given me a core dump where the fault
occurred in the __lll_unlock_elision function as shown in that forum post I
too would have suspected a hardware fault: either outright broken hardware
or buggy CPU microcode.

-- 
Kurtis Rader
Caretaker of the exceptional canines Junior and Hank

**Comment by klen** [comment]
Thank you @krader1961 Some times the issue happens when vim uses different python versions.
