### ISSUE TITLE
Python logging don't work when run current code in vim

### ISSUE THREAD

**Issue by ThinkCats** [klen/python-mode#705]
Here is my test code:
Test.py

```
import logging
logging.basicConfig(level=logging.INFO)

logging.warning('hahah')
logging.info('heheda')

```

There will print nothing on the screen when I run my current python code in vim . However, the code can print the warning and info message when I use "python3   Test.py " .

I don't know why , I lost some config ? 

Here is my vim config:

```
let g:pymode_rope = 0

let g:pymode_python = 'python3'

" Documentation
let g:pymode_doc = 1
let g:pymode_doc_key = 'K'

"Linting
let g:pymode_lint = 1
let g:pymode_lint_checker = "pyflakes,pep8"
" Auto check on save
let g:pymode_lint_write = 1

" Support virtualenv
let g:pymode_virtualenv = 1

" Enable breakpoints plugin
let g:pymode_breakpoint = 1
let g:pymode_breakpoint_bind = '<leader>b'

" syntax highlighting
let g:pymode_syntax = 1
let g:pymode_syntax_all = 1
let g:pymode_syntax_indent_errors = g:pymode_syntax_all
let g:pymode_syntax_space_errors = g:pymode_syntax_all

" Don't autofold code
let g:pymode_folding = 0

" Run Python Code
let g:pymode_run = 1

let g:pymode_rope_goto_definition_bind = "<C-]>"

let g:pymode_run_bind = "<C-b>"

noremap <F8> :PymodeLintAuto<CR>


```

**Comment by fmv1992** [comment]
It is not a pymode bug.

The issue is that logging outputs to channel 2 and pymode run outputs from channel 1.

Read more on:

https://workaround.org/linuxtip/pipes

**Comment by ThinkCats** [comment]
@fmv1992  thanks a lot . I am a beginner learning Python,  is there any ways to resolve  this issue ?

**Comment by fmv1992** [comment]
You are welcome!

I would not try to solve it within pymode/vim since they are not the cause of the issue

Alternatives that come to my mind are:
1) Use vim to write the software but run your code in a console (not very handy but not so painful neither)
2) Tweak your code to redirect the other channels to stdout during the development phase. Do not forget to remove this tweak when distributing the software. Check more details here: http://stackoverflow.com/questions/14058453/making-python-loggers-output-all-messages-to-stdout-in-addition-to-log (keywords: python redirect logging to stdout)

**Comment by ThinkCats** [comment]
@fmv1992  Thanks again.  I have tried the ways what you said several days ago. And now,  I run my python code , and show the result in another console window using my custom vim config ( config:  noremap <silent> <C-b> <Esc>:w !python3 % <CR>), maybe this is the simplest way.
